---
abstract: 'Configurator implementation with Config::Any'
author:
  - 'Oliver Gorwits <oliver@cpan.org>'
build_requires:
  Config::Tiny: 0
  Log::Dispatch::Config: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200013, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Dispatch-Configurator-Any
requires:
  Carp: 0
  Config::Any: 0.15
  Log::Dispatch: 2.23
  Log::Dispatch::Configurator: 0
  Sys::Syslog: 0.25
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Log-Dispatch-Configurator-Any
  homepage: https://github.com/ollyg/Log-Dispatch-Configurator-Any/wiki
  repository: git://github.com/ollyg/Log-Dispatch-Configurator-Any.git
version: 1.122640
